var songs = [
	{
		'id': 'EErSKhC0CZs',
		'title': 'You Make My Dreams',
		'year': '1980',
		'album': 'Voices',
		'slug': 'you-make-my-dreams',
		'thumbnail': 'youmakemydreams.jpg',
	},
	{
		'id': 'McOAjzart78',
		'title': 'Possession Obsession',
		'year': '1984',
		'album': 'Big Bam Boom',
		'slug': 'posssession-obsession',
		'thumbnail': 'bigbamboom.jpg',
	},
	{
		'id': 'D00M2KZH1J0',
		'title': 'Out of Touch',
		'year': '1984',
		'album': 'Big Bam Boom',
		'slug': 'out-of-touch',
		'thumbnail': 'outoftouch.jpg',
	},
	{
		'id': 'JsntlJZ9h1U',
		'title': 'Private Eyes',
		'year': '1981',
		'album': 'Private Eyes',
		'slug': 'private-eyes',
		'thumbnail': 'privateyes.jpg',
	},
	{
		'id': 'yRYFKcMa_Ek',
		'title': 'Maneater',
		'year': '1982',
		'album': 'H2O',
		'slug': 'maneater',
		'thumbnail': 'maneater.jpg',
	},
	{
		'id': 'vZZngTkp54I',
		'title': "She's Gone",
		'year': '1973',
		'album': 'Abandoned Luncheonette',
		'slug': 'shes-gone',
		'thumbnail': 'shesgone.png',
	},
	{
		'id': '6EwOOdrx4G0',
		'title': 'Rich Girl',
		'year': '1976',
		'album': 'Bigger Than Both of Us',
		'slug': 'rich-girl',
		'thumbnail': 'richgirl.jpg',
	},
	{
		'id': 'Q3F4c7E9IBU',
		'title': 'Method of Modern Love',
		'year': '1984',
		'album': 'Big Bam Boom',
		'slug': 'method-of-modern-love',
		'thumbnail': 'bigbamboom.jpg',
	},
	{
		'id': 'rrWXFxLIV3w',
		'title': 'Your Imagination',
		'year': '1981',
		'album': 'Private Eyes',
		'slug': 'your-imagination',
		'thumbnail': 'yourimagination.png',
	},
	{
		'id': '_R5xIdXwNMk',
		'title': "Say It Isn't So",
		'year': '1983',
		'album': "Rock 'n Soul, Part 1",
		'slug': 'say-it-isnt-so',
		'thumbnail': 'sayitisntso.jpg',
	},
	{
		'id': '-oiqiYdWXiM',
		'title': 'Family Man',
		'year': '1982',
		'album': 'H2O',
		'slug': 'family-man',
		'thumbnail': 'familyman.jpg',
	},
	{
		'id': 'ccenFp_3kq8',
		'title': "I Can't Go For That (No Can Do)",
		'year': '1981',
		'album': 'Private Eyes',
		'slug': 'i-cant-go-for-that',
		'thumbnail': 'icantgoforthat.jpg',
	},
];